name: 获取组播ip

on:
#  schedule:
#    - cron: '0 7,22 * * *'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests selenium futures eventlet

      - name: 获取组播ip
        run: |
          cd $GITHUB_WORKSPACE
          python ./zubo_test.py
                    
      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "更新组播ip"
          git push
